-- Optional hardening tables for the studio editor and privacy-friendly site telemetry.
-- Run this once in the Supabase SQL editor. Existing portfolio tables are not changed.

create table if not exists public.portfolio_history (
  id bigint generated by default as identity primary key,
  owner uuid not null references auth.users(id) on delete cascade,
  label text not null default 'portfolio saved',
  content jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.portfolio_history enable row level security;

drop policy if exists "owners can read portfolio history" on public.portfolio_history;
create policy "owners can read portfolio history"
on public.portfolio_history for select to authenticated
using (auth.uid() = owner);

drop policy if exists "owners can add portfolio history" on public.portfolio_history;
create policy "owners can add portfolio history"
on public.portfolio_history for insert to authenticated
with check (auth.uid() = owner);

drop policy if exists "owners can delete portfolio history" on public.portfolio_history;
create policy "owners can delete portfolio history"
on public.portfolio_history for delete to authenticated
using (auth.uid() = owner);

create index if not exists portfolio_history_owner_created_idx
on public.portfolio_history (owner, created_at desc);

create table if not exists public.portfolio_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('page_view', 'error')),
  path text not null default '/',
  referrer_host text not null default '',
  viewport text not null default 'unknown',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.portfolio_events enable row level security;

drop policy if exists "visitors can add anonymous site events" on public.portfolio_events;
create policy "visitors can add anonymous site events"
on public.portfolio_events for insert to anon, authenticated
with check (
  char_length(path) <= 240
  and char_length(referrer_host) <= 180
  and char_length(viewport) <= 20
);

-- Events are intentionally not publicly readable. View them from the Supabase dashboard.
create index if not exists portfolio_events_created_idx
on public.portfolio_events (created_at desc);
